### ISSUE TITLE
Major Node.js upgrades are always handled as breaking changes

### ISSUE THREAD

**Issue by StarpTech** [nats-io/node-nuid#18]
I notice an error during upgrading NUID from 1.0.0 to 1.1.0 because my project supports Node 6.
Handle major node updates always as breaking changes.
Related PR: https://github.com/nats-io/node-nuid/pull/13

**Comment by StarpTech** [comment]
The same error I got with upgrading from Nats 1.2 to 1.3

**Comment by aricart** [comment]
Hi @StarpTech, I hear you. Would a minor bump change be sufficient for you. I don't believe we should major change a version in this case, as likely there are security issues reported against the EOL software.

**Comment by StarpTech** [comment]
Hi @aricart thanks, I could handle that. IHO, changes in major versions in nodejs should be handled as major releases because it requires intervention. In yarn your build will fail if your engine field does not match this is what I got. Therefore not everybody can easily upgrade the nodejs version due to api incompatibilities or cascading failures etc... This is definitely no task to do in a "patch" release. 

A minor release will also not enforce users from changing the nodejs version but a major version will clearly communicate that something broader happened and in order to get new updates you have to update.

**Comment by StarpTech** [comment]
Here you read that guideline:

https://github.com/nodejs/package-maintenance/blob/master/docs/versioning.md#other-versioning-requirements

> Increasing the minimum required version of node is a breaking change and should be accompanied by major semver change.
